version: "3.2"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT_KEY: dev
    restart: unless-stopped
    links:
      - mysql
    networks:
      - book-store
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@mysql:3306/book-store?serverVersion=5.7

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8002:80
    links:
      - mysql
    networks:
      - book-store
  mysql:
    image: mysql
    platform: linux/amd64
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - book-store-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book-store
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin12345
    networks:
      - book-store

networks:
  book-store:
    driver: overlay
    attachable: true

volumes:
  book-store-data: